# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 07:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('utility', '0001_initial'),
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverTime',
            fields=[
                ('taskunitspointsbasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utility.TaskUnitsPointsBaseModel')),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('time_from', models.TimeField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('time_to', models.TimeField(blank=True, null=True)),
                ('total_in_hrs', models.CharField(blank=True, max_length=255, null=True)),
                ('rate_per_hour', models.DecimalField(decimal_places=2, default='0.00', max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, default='0.00', max_digits=12)),
                ('comments', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('approve', 'approve'), ('reject', 'reject')], max_length=32)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='OverTime', to='hr.Employee')),
                ('overtime_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='OverTimeManager', to='hr.Employee')),
            ],
            bases=('utility.taskunitspointsbasemodel',),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('taskunitspointsbasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utility.TaskUnitsPointsBaseModel')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('project_cost', models.DecimalField(decimal_places=2, default='0.00', max_digits=12)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default='0.00', max_digits=12)),
                ('actual_cost', models.DecimalField(decimal_places=2, default='0.00', max_digits=12)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('pending', 'pending'), ('completed', 'completed')], max_length=32)),
            ],
            bases=('utility.taskunitspointsbasemodel',),
        ),
        migrations.CreateModel(
            name='ProjectManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('active', 'active'), ('inactive', 'inactive')], max_length=32)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ProjectManage', to='project_management.Project')),
                ('project_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hr.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('total_units_task', models.DecimalField(decimal_places=2, default='0.00', max_digits=12)),
                ('estimated_time_duration', models.DecimalField(decimal_places=2, default='0.00', max_digits=12, verbose_name='Estimated Time Duration in Hours')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hr.Employee')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_createdby', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_modifiedby', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ProjectTask', to='project_management.Project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaskPerformed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_units_completed', models.DecimalField(decimal_places=2, default='0.00', max_digits=12)),
                ('percent_completion', models.DecimalField(decimal_places=2, default='0.00', max_digits=12)),
                ('total_task_time', models.DecimalField(decimal_places=2, default='0.00', max_digits=12, verbose_name='Total task time in Hours')),
                ('comments', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project_management.Task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskPerformedReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('pending', 'pending'), ('completed', 'completed')], max_length=32)),
                ('employee_achievement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hr.Employee_Achievement')),
                ('project_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utility.UserProfile')),
                ('taskperformed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project_management.TaskPerformed')),
            ],
        ),
        migrations.AddField(
            model_name='overtime',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project_management.Task'),
        ),
    ]
