# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_auto_20170321_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='date_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
