# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 09:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_training_date_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='is_freedomfighter',
        ),
    ]
