# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 19:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20170323_0118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warehousemanager',
            old_name='employee',
            new_name='manager',
        ),
    ]
