# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 19:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0001_initial'),
        ('inventory', '0003_auto_20170323_0122'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default='0.00', max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default='0.00', max_digits=12)),
                ('tax', models.DecimalField(decimal_places=2, default='0.00', max_digits=12)),
                ('date_added', models.DateField(blank=True, null=True)),
                ('slug', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SaleProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default='0.00', max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default='0.00', max_digits=12)),
                ('tax', models.DecimalField(decimal_places=2, default='0.00', max_digits=12)),
                ('date_added', models.DateField(blank=True, null=True)),
                ('slug', models.CharField(blank=True, max_length=255, null=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Item')),
            ],
        ),
        migrations.RemoveField(
            model_name='products',
            name='item',
        ),
        migrations.RemoveField(
            model_name='products',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='buy',
            name='products',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='products',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.AddField(
            model_name='saleproducts',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Sale'),
        ),
        migrations.AddField(
            model_name='saleproducts',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utility.Unit'),
        ),
        migrations.AddField(
            model_name='buyproducts',
            name='buy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Buy'),
        ),
        migrations.AddField(
            model_name='buyproducts',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Item'),
        ),
        migrations.AddField(
            model_name='buyproducts',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utility.Unit'),
        ),
    ]
